# NUMPY CrashCourse

In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [5]:
my_list = [0,1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
arr= np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


# Arrange Function

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,20,5)

array([10, 15])

In [15]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.arange(20,10) #1st argument should be less than 2nd

array([], dtype=int32)

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.zeros(5) #hyperparameter tuning

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros(5,dtype=int)#hyperparameter tuning

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros([2,2]) #2-dimensional array

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros([5,4]) #ndarray with 5 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros([10,10]) #10x10 matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones(2) #array of ones

array([1., 1.])

In [27]:
np.ones(2, dtype=int) #array of ones with integer type

array([1, 1])

In [26]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
arr

array([0, 1, 2, 3, 4, 5])

In [35]:
#rand(3,2)

In [36]:
#random.rand(3,2) #3 rows and 2 columns of random numbers

In [34]:
np.random.rand(3,2) #3 rows and 2 columns of random numbers

array([[0.56221809, 0.59790121],
       [0.79779397, 0.32252512],
       [0.13413751, 0.08195099]])

In [38]:
np.random.rand(3)

array([0.85930191, 0.34215677, 0.05399495])

In [42]:
np.random.randint(4,6)

4

In [50]:
np.random.randint(0,10) #random integer between 0 and 10

3

In [54]:
np.random.randint(0,10,4) #4 random integers between 0 and 10

array([5, 7, 4, 5])

In [56]:
np.random.randint(0,10,5) #5 random integers between 0 and 10

array([6, 9, 0, 8, 4])

In [64]:
n=np.random.randint(10,40,(8,10)) #8 rows and 10 columns of random integers between 10 and 40
n

array([[14, 39, 23, 36, 16, 27, 17, 31, 30, 24],
       [21, 17, 11, 19, 24, 20, 30, 22, 20, 38],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [17, 33, 34, 17, 15, 37, 29, 19, 33, 26],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36],
       [19, 32, 14, 30, 13, 38, 13, 14, 18, 29],
       [31, 26, 23, 10, 26, 34, 28, 16, 26, 20],
       [38, 24, 28, 25, 12, 12, 14, 36, 14, 25]])

In [65]:
n[0] #1st row

array([14, 39, 23, 36, 16, 27, 17, 31, 30, 24])

In [66]:
n[5] #6th row

array([19, 32, 14, 30, 13, 38, 13, 14, 18, 29])

In [ ]:
n

array([[14, 39, 23, 36, 16, 27, 17, 31, 30, 24],
       [21, 17, 11, 19, 24, 20, 30, 22, 20, 38],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [17, 33, 34, 17, 15, 37, 29, 19, 33, 26],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36],
       [19, 32, 14, 30, 13, 38, 13, 14, 18, 29],
       [31, 26, 23, 10, 26, 34, 28, 16, 26, 20],
       [38, 24, 28, 25, 12, 12, 14, 36, 14, 25]])

In [68]:
n[0:6] #rows 0 to 5

array([[14, 39, 23, 36, 16, 27, 17, 31, 30, 24],
       [21, 17, 11, 19, 24, 20, 30, 22, 20, 38],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [17, 33, 34, 17, 15, 37, 29, 19, 33, 26],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36],
       [19, 32, 14, 30, 13, 38, 13, 14, 18, 29]])

In [ ]:
n[::-1] #reverse the rows

array([[38, 24, 28, 25, 12, 12, 14, 36, 14, 25],
       [31, 26, 23, 10, 26, 34, 28, 16, 26, 20],
       [19, 32, 14, 30, 13, 38, 13, 14, 18, 29],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36],
       [17, 33, 34, 17, 15, 37, 29, 19, 33, 26],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [21, 17, 11, 19, 24, 20, 30, 22, 20, 38],
       [14, 39, 23, 36, 16, 27, 17, 31, 30, 24]])

In [ ]:
n[::-1] #reverse the Matrix

array([[38, 24, 28, 25, 12, 12, 14, 36, 14, 25],
       [31, 26, 23, 10, 26, 34, 28, 16, 26, 20],
       [19, 32, 14, 30, 13, 38, 13, 14, 18, 29],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36],
       [17, 33, 34, 17, 15, 37, 29, 19, 33, 26],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [21, 17, 11, 19, 24, 20, 30, 22, 20, 38],
       [14, 39, 23, 36, 16, 27, 17, 31, 30, 24]])

In [71]:
n[::2] #every 2nd row

array([[14, 39, 23, 36, 16, 27, 17, 31, 30, 24],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36],
       [31, 26, 23, 10, 26, 34, 28, 16, 26, 20]])

In [ ]:
n #rows 0 to 5

array([[14, 39, 23, 36, 16, 27, 17, 31, 30, 24],
       [21, 17, 11, 19, 24, 20, 30, 22, 20, 38],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [17, 33, 34, 17, 15, 37, 29, 19, 33, 26],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36],
       [19, 32, 14, 30, 13, 38, 13, 14, 18, 29],
       [31, 26, 23, 10, 26, 34, 28, 16, 26, 20],
       [38, 24, 28, 25, 12, 12, 14, 36, 14, 25]])

In [75]:
n[0:5] #rows 0 to 4

array([[14, 39, 23, 36, 16, 27, 17, 31, 30, 24],
       [21, 17, 11, 19, 24, 20, 30, 22, 20, 38],
       [13, 28, 39, 31, 11, 14, 26, 33, 39, 15],
       [17, 33, 34, 17, 15, 37, 29, 19, 33, 26],
       [24, 17, 22, 32, 36, 13, 34, 28, 10, 36]])

In [74]:
n[0,5] #element at 1st row and 6th column

27

In [76]:
n[5,-3] #element at 6th row and 3rd last column

14

# Reshape

In [ ]:
np.arange(1,13).reshape(4,3) #reshaping 1D array to 2D array with 4 rows and 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(1,12) #reshaping 1D array to 2D array with 1 row and 12 columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [83]:
np.arange(1,13).reshape(6,2) #reshaping 1D array to 2D array with 6 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])