# Numpy CrashCourse 


In [154]:
import numpy as np

In [155]:
np.__version__

'1.26.4'

In [156]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [157]:
type(my_list)

list

In [158]:
my_list

[0, 1, 2, 3, 4, 5]

In [159]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [160]:
print(type(arr))

<class 'numpy.ndarray'>


In [161]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [163]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [164]:
np.arange(20,10) # 1st argument < 2nd argument 

array([], dtype=int32)

In [165]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [166]:
np.zeros(5) # Parameter tuning

array([0., 0., 0., 0., 0.])

In [167]:
np.zeros(5,dtype=int) #hyperparameter tuning

array([0, 0, 0, 0, 0])

In [168]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [169]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [170]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [171]:
np.ones(2)

array([1., 1.])

In [172]:
np.ones(2, dtype=int)

array([1, 1])

In [173]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [174]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [175]:
arr

array([0, 1, 2, 3, 4, 5])

In [176]:
#rand(3,2)

In [177]:
#random.rand(3,2)

In [178]:
np.random.rand(3,2)

array([[0.26890623, 0.45723716],
       [0.01514005, 0.91415744],
       [0.65510567, 0.71822456]])

In [179]:
np.random.rand(3)

array([0.12893454, 0.71252603, 0.7106589 ])

In [180]:
np.random.randint(4,6)

4

In [181]:
np.random.randint(0,10)

1

In [182]:
np.random.randint(0,10,4) 

array([0, 6, 2, 4])

In [183]:
np.random.randint(0,10,5) 

array([3, 8, 8, 8, 5])

In [184]:
np.random.randint(0,10,6)

array([7, 1, 8, 9, 2, 1])

In [185]:
n= np.random.randint(0,10,6)
n

array([4, 0, 5, 2, 9, 5])

In [186]:
n= np.random.randint(10,40,(8,10))
n

array([[10, 30, 17, 27, 23, 25, 29, 15, 26, 21],
       [18, 38, 36, 22, 12, 11, 23, 26, 29, 19],
       [23, 14, 39, 18, 12, 17, 34, 27, 14, 17],
       [27, 31, 11, 31, 29, 17, 32, 22, 36, 35],
       [36, 14, 35, 15, 39, 19, 23, 16, 14, 27],
       [35, 29, 10, 36, 23, 30, 39, 17, 28, 17],
       [16, 18, 16, 31, 25, 34, 23, 19, 36, 14],
       [32, 39, 13, 19, 17, 37, 21, 35, 18, 20]])

In [187]:
n[0]

array([10, 30, 17, 27, 23, 25, 29, 15, 26, 21])

In [188]:
n= np.random.randint(10,40,(8,10))
n

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [38, 28, 13, 38, 31, 24, 20, 22, 26, 23]])

In [189]:
n[5]

array([33, 39, 15, 24, 35, 24, 34, 37, 26, 22])

In [190]:
n

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [38, 28, 13, 38, 31, 24, 20, 22, 26, 23]])

In [191]:
n[0:6]

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22]])

In [192]:
n

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [38, 28, 13, 38, 31, 24, 20, 22, 26, 23]])

In [193]:
n[::-1] # reverse

array([[38, 28, 13, 38, 31, 24, 20, 22, 26, 23],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [11, 17, 14, 37, 21, 12, 39, 10, 32, 32]])

In [194]:
n

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [38, 28, 13, 38, 31, 24, 20, 22, 26, 23]])

In [195]:
n[::1] # forward

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [38, 28, 13, 38, 31, 24, 20, 22, 26, 23]])

In [196]:
n[::2] # forward

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25]])

In [197]:
n

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [38, 28, 13, 38, 31, 24, 20, 22, 26, 23]])

In [198]:
n[0]

array([11, 17, 14, 37, 21, 12, 39, 10, 32, 32])

In [199]:
n[0:5]

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33]])

In [200]:
n[0,5]

12

In [201]:
n

array([[11, 17, 14, 37, 21, 12, 39, 10, 32, 32],
       [17, 34, 39, 11, 13, 36, 31, 20, 16, 22],
       [35, 39, 11, 27, 12, 29, 26, 39, 33, 34],
       [20, 23, 17, 10, 35, 20, 30, 33, 26, 14],
       [11, 26, 10, 11, 30, 38, 35, 19, 31, 33],
       [33, 39, 15, 24, 35, 24, 34, 37, 26, 22],
       [29, 10, 22, 15, 15, 15, 34, 38, 39, 25],
       [38, 28, 13, 38, 31, 24, 20, 22, 26, 23]])

In [202]:
n[5,-3] # 5th row and last 3rd column

37

In [203]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [204]:
# Transpose of array
e1=np.array([[1,2],[3,4]])
transpose=np.transpose(e1) # Transpose of array
print("Transposed of array:\n",transpose)

Transposed of array:
 [[1 3]
 [2 4]]


In [205]:
a2=9
b2=8

In [206]:
# Stacking of array
e2=np.array([[1,2],[3,4]])
e3=np.array([[5,6],[7,8]])
stack=np.vstack([a2,b2]) # Stack a and b vertically 
print("Stacked array:\n",stack)

Stacked array:
 [[9]
 [8]]
